
# Fire Webhook
# Tells plaid to initiate webhook calls as if new sync events occured, for the purposes of testing.
post https://sandbox.plaid.com/sandbox/item/fire_webhook
Content-Type: application/json

{
    "client_id": "{{plaid-client-id}}",
    "secret": "{{plaid-secret}}",
    "access_token": "{{plaid-access-token}}",
    "webhook_code": "DEFAULT_UPDATE"
}


###


# Fire Webhook Receiver (mock webhook call)
# This mocks the sync call that Plaid will make to this endpiont, sending a Plaid item_id.
# Using the provided item ID, the function calls back to plaid to retrieve new transactions.
# The new transactions are enqueued for notifications.

post http://localhost:7072/api/plaidTransactionsSync
Content-Type: application/json

{
  "webhook_type": "TRANSACTIONS",
  "webhook_code": "SYNC_UPDATES_AVAILABLE",
  "item_id": "ogeAZK35BDcQj38gV4kJFjGpnGQGxXtRx78lB",
  "initial_update_complete": true,
  "historical_update_complete": false,
  "environment": "sandbox"
}